# Generated by Django 2.2.9 on 2020-01-23 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20200121_1120'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='group',
        #     name='curator',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.Teacher'),
        # ),
    ]
