# Generated by Django 2.2.9 on 2020-01-23 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20200123_1244'),
        ('students', '0008_auto_20200123_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.Teacher'),
        ),
        migrations.AlterField(
            model_name='group',
            name='curator',
            field=models.CharField(default=10, max_length=200),
            preserve_default=False,
        ),
    ]
