# Generated by Django 2.2.9 on 2020-01-23 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20200123_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='curator',
        ),
        migrations.RemoveField(
            model_name='group',
            name='teacher',
        ),
    ]
