# Generated by Django 2.2.9 on 2020-01-25 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_group_curator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='curator',
        ),
    ]
