# Generated by Django 2.2.9 on 2020-02-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_auto_20200129_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='active_user',
            field=models.BooleanField(default=False),
        ),
    ]
