# Generated by Django 2.2.9 on 2020-02-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_student_active_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=6)),
                ('time_delta', models.CharField(max_length=50)),
                ('user_id', models.IntegerField()),
                ('user_email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
