# Generated by Django 2.2.9 on 2020-02-08 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_auto_20200208_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logger',
            name='time_delta',
        ),
    ]
