# Generated by Django 2.2.9 on 2020-01-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='telephone',
            field=models.CharField(max_length=30),
        ),
    ]
