# Generated by Django 2.2.9 on 2020-01-28 19:10

from django.db import migrations


def forward(apps, schema_editor):
    Teacher = apps.get_model('teachers', 'Teacher')
    for teacher in Teacher.objects.all().only('id', 'telephone').iterator():
        teacher.telephone = ''.join(x for x in teacher.telephone if x.isdigit())
        teacher.save(update_fields=['telephone'])


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20200123_1244'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
